version: '3'

services:
  auth:
    image: alessandrotalmi/brittany-auth-service-dev
    environment:
      - DB=mongodb://database:27017/brittany_auth
      - PORT=80
    ports:
      - 81:80
  database:
    image: mongo
    volumes:
      - database_data:/data/db

volumes:
  database_data:
