version: '3'

services:
  persistence:
    image: alessandrotalmi/brittany-persistence-service-dev
    environment:
      - DB=mongodb://database:27017/brittany_persistence
      - PORT=80
      - FARMER_TOKEN_SECRET=devFarmerTokenSecret
      - AGENT_TOKEN_SECRET=devAgentTokenSecret
    ports:
      - 80:80
  database:
    image: mongo
    volumes:
      - database_data:/data/db

volumes:
  database_data: