version: '3'

services:
  web_client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_PERSISTENCE_SERVICE_ADDRESS=http://localhost
      - REACT_APP_PERSISTENCE_SERVICE_PORT=80
    ports:
      - 3000:3000
    image: web_client
