name: Edge CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install lcov
      run: sudo apt-get install -y lcov
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install library dependencies
      run: pio lib -g install 1
    - name: Run PlatformIO
      run: cd ./edge && pio test
    - name: Check test coverage
      uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
      with:
        coverage-file: edge/filtered_lcov.info
        minimum-coverage: 90
  deploy-dev-image:
    needs: build
    if: github.ref == 'refs/heads/edge'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./edge
    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/brittany-edge-dev:latest
        - name: Push the latest Docker image
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/brittany-edge-dev:latest
