name: Push Edge's production Image to Docker Hub

on:
  workflow_run:
    workflows: ["Edge CI"]
    branches:
      - master
    types:
      - completed

jobs:
  deploy-dev-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./edge
    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/brittany-edge:latest
        - name: Push the latest Docker image
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/brittany-edge:latest